version: "3.9"

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
      - ./data:/data
    environment:
      - ENV=dev
      - DATA_DIR=/data
  tests:
    build: .
    command: pytest -q --cov=backend tests
    volumes:
      - .:/app           # project root – includes backend + tests 